### ISSUE TITLE
some errors being written to .xsession-errors:

### ISSUE THREAD

**Issue by leetwanker** [collinss/cinnamon-places-center#11]
(cinnamon:2543): Cjs-WARNING **: JS ERROR: Exception in callback for signal: destroy: Error: No signal connection undefined found
_disconnect@resource:///org/gnome/gjs/modules/signals.js:74
PopupMenuBase.prototype._connectItemSignals/<@/usr/share/cinnamon/js/ui/popupMenu.js:971
_emit@resource:///org/gnome/gjs/modules/signals.js:124
PopupBaseMenuItem.prototype.destroy@/usr/share/cinnamon/js/ui/popupMenu.js:149
MyApplet.prototype.buildTrashItem@/home/justin/.local/share/cinnamon/applets/placesCenter@scollins/applet.js:565

I've not seen any loss in functionality but figured I'd report it anyway.

**Comment by collinss** [comment]
Thanks for taking the time to report this. Can you tell me what versions of Cinnamon and places center you are using? Also, steps to reproduce would be helpful if you have them, since I can't seem to reproduce it here.

**Comment by leetwanker** [comment]
I'll keep an eye on .xsession-errors and see if I can figure out when it's happening. In the meantime, here's an one I'm getting when I enter into an sftp share with nemo (not through placesCenter).

(cinnamon:2528): Cjs-WARNING **: JS ERROR: Exception in callback for signal: destroy: Error: No signal connection 3 found
_disconnect@resource:///org/gnome/gjs/modules/signals.js:74
PopupMenuBase.prototype._connectItemSignals/<@/usr/share/cinnamon/js/ui/popupMenu.js:967
_emit@resource:///org/gnome/gjs/modules/signals.js:124
PopupBaseMenuItem.prototype.destroy@/usr/share/cinnamon/js/ui/popupMenu.js:149
MyApplet.prototype.buildTrashItem@/home/justin/.local/share/cinnamon/applets/placesCenter@scollins/applet.js:565
MyApplet.prototype.buildUserSection@/home/justin/.local/share/cinnamon/applets/placesCenter@scollins/applet.js:457
MyApplet.prototype.updateVolumes@/home/justin/.local/share/cinnamon/applets/placesCenter@scollins/applet.js:561

Cinnamon version: 2.4.6+rebecca
Places Center    "version": "2.1",

**Comment by leetwanker** [comment]
(cinnamon:2528): Cjs-WARNING **: JS ERROR: Exception in callback for signal: destroy: Error: No signal connection undefined found
_disconnect@resource:///org/gnome/gjs/modules/signals.js:74
PopupMenuBase.prototype._connectItemSignals/<@/usr/share/cinnamon/js/ui/popupMenu.js:971
_emit@resource:///org/gnome/gjs/modules/signals.js:124
PopupBaseMenuItem.prototype.destroy@/usr/share/cinnamon/js/ui/popupMenu.js:149
MyApplet.prototype.buildTrashItem@/home/justin/.local/share/cinnamon/applets/placesCenter@scollins/applet.js:565

This one seems to pop up when I send a file to Trash. Not when I delete it permanently.

**Comment by collinss** [comment]
Thanks, I just found one in my x-session errors as well. I'm not sure what caused it though. I'll try to do some more testing tomorrow.

**Comment by leetwanker** [comment]
Thanks. And thanks for the applet, big time saver.

**Comment by collinss** [comment]
You're welcome. It's always good to hear that some else finds one of my applets as useful as I do.

**Comment by collinss** [comment]
https://github.com/collinss/cinnamon-places-center/commit/99435f0d68ae5e60e34038ad78c80ec6ecde8018 should fix it. I'll try to post an update to the spices website soon. Thanks for bringing this to my attention.
