### ISSUE TITLE
[Feature request] Bookmark shortcut for middle-cick

### ISSUE THREAD

**Issue by kehugter** [collinss/cinnamon-places-center#13]
Right now the middle-click has no assignment, as far as I can tell. Could it be used to open a previously assigned location, without showing the menu?

**Comment by collinss** [comment]
Are you talking about the applet itself? - eg, middle click the panel -> opens home folder in nemo? I might consider something along these lines.

**Comment by kehugter** [comment]
Indeed, as you describe.

**Comment by collinss** [comment]
This will be in the next release (I'm not entirely sure when that will be), but if you really want to try it out now, you can download from here, and unpack in ```~/.local/share/cinnamon/applets/placesCenter@scollins```.
