### ISSUE TITLE
[Feature Request] enable to adjust column width when meet long filename or path

### ISSUE THREAD

**Issue by highwindmx** [collinss/cinnamon-places-center#5]
I tried search ".sh"(I don't know why *.sh not work) and some of these files have quite a long path, then path column expand and squeeze the file(name) column to unable to see the names, 
the problem is the file column width can not adjust by using bi-arrow until I make the whole search tool window larger. 

I have not tested yet but I am afraid what if a path is so long then even the whole window width can't hold it?

**Comment by collinss** [comment]
Fixed
