### ISSUE TITLE
[Bug?]lost in loop when search with symlink

### ISSUE THREAD

**Issue by highwindmx** [collinss/cinnamon-places-center#6]
![linuxmint17](https://cloud.githubusercontent.com/assets/6413481/3229740/fef5c76a-f099-11e3-8fb8-29742887ecea.png)
look at this search, I search "placecenter" with symlink in whole filesystem, but it seems that the search is stuck in a loop(3mins later still in that place).

**Comment by collinss** [comment]
This is now fixed.
