### ISSUE TITLE
[Feature Request] support search by wild-card characters

### ISSUE THREAD

**Issue by highwindmx** [collinss/cinnamon-places-center#7]
Consider about this applet aim as a simple tool for fast search, 
actually it is not that important. :)
take your time, and love your applet.

**Comment by collinss** [comment]
I just added support for regular expressions in the search tool. Perhaps it's a little bit more powerful than what you were looking for, but strangely enough, it was actually easier to implement than a few simple wild-card characters (and probably faster as well) :p

I haven't posted the updates to the Spices site yet, but it should be there in the next few days.
